# Generated by Django 3.2.12 on 2022-04-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_decompiler_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='binary',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='binary',
            name='featured_name',
            field=models.TextField(max_length=32, null=True),
        ),
    ]
